spring.application.name=github-actions-demo
server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

demo.version=${APP_VERSION:local}
demo.commit=${GIT_COMMIT:unknown}
demo.environment=${APP_ENVIRONMENT:DEV}
